# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout this repo
      - uses: actions/checkout@v3
        with:
          path: 'hacs'
      # Clone LaMetric SKY Integration
      - uses: actions/checkout@v3
        with:
          repository: 'spyfly/ha-core'
          ref: 'lametric_sky'
          path: 'ha-core'

      # Copy lametric integration folder
      - name: Copy lametric integration folder
        run: cp -R ha-core/homeassistant/components/lametric hacs/custom_components/lametric
        
      - name: Replace Manifest Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "demetriek==0.4.0"
          replace: "demetriek @ git+https://github.com/spyfly/python-demetriek@lametric_sky"
          include: "hacs/custom_components/lametric/manifest.json"
          regex: false
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git*'
          directory: 'hacs'
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "release.zip"
          bodyFile: "hacs/info.md"
